"""add color to annotation

Revision ID: 0f4f8dfe77c1
Revises: fbcbd179bfba
Create Date: 2025-12-20 23:06:16.357894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types


# revision identifiers, used by Alembic.
revision: str = '0f4f8dfe77c1'
down_revision: Union[str, None] = 'fbcbd179bfba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_category', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
