"""rename collaboratorrole

Revision ID: 71bb37e4bf8c
Revises: 0f4f8dfe77c1
Create Date: 2025-12-22 15:37:26.170167

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types


# revision identifiers, used by Alembic.
revision: str = "71bb37e4bf8c"
down_revision: Union[str, None] = "0f4f8dfe77c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("collaborator", schema=None) as batch_op:
        batch_op.alter_column("project_role", new_column_name="role")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("collaborator", schema=None) as batch_op:
        batch_op.alter_column("role", new_column_name="project_role")

    # ### end Alembic commands ###
