"""add_analysis_table

Revision ID: 1115871d7f82
Revises: fbcbd179bfba
Create Date: 2025-12-16 20:09:18.540235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types


# revision identifiers, used by Alembic.
revision: str = '1115871d7f82'
down_revision: Union[str, None] = 'fbcbd179bfba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_category',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('TAG', 'SCORE', name='analysistype'), nullable=False),
    sa.Column('min_value', sa.Integer(), nullable=True),
    sa.Column('max_value', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_analysis_category_project_id_project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_category')),
    sa.UniqueConstraint('id', name=op.f('uq_analysis_category_id')),
    sa.UniqueConstraint('project_id', 'name', name='unique_project_category_name')
    )
    op.create_table('message_annotation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name=op.f('fk_message_annotation_message_id_message')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_message_annotation_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_annotation')),
    sa.UniqueConstraint('id', name=op.f('uq_message_annotation_id'))
    )
    op.create_table('annotation_value',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('annotation_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('value_int', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['annotation_id'], ['message_annotation.id'], name=op.f('fk_annotation_value_annotation_id_message_annotation')),
    sa.ForeignKeyConstraint(['category_id'], ['analysis_category.id'], name=op.f('fk_annotation_value_category_id_analysis_category')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_annotation_value')),
    sa.UniqueConstraint('annotation_id', 'category_id', name='unique_annotation_category'),
    sa.UniqueConstraint('id', name=op.f('uq_annotation_value_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annotation_value')
    op.drop_table('message_annotation')
    op.drop_table('analysis_category')
    # ### end Alembic commands ###
