"""add ANNOTATOR to CollaboratorRole

Revision ID: 64a392d65079
Revises: 71bb37e4bf8c
Create Date: 2025-12-22 18:20:37.318216

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types


# revision identifiers, used by Alembic.
revision: str = "64a392d65079"
down_revision: Union[str, None] = "71bb37e4bf8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("collaborator", schema=None) as batch_op:
        batch_op.alter_column(
            "role",
            existing_type=sa.VARCHAR(length=6),
            type_=sa.Enum(
                "VIEWER", "ANNOTATOR", "EDITOR", "ADMIN", name="collaboratorrole"
            ),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("collaborator", schema=None) as batch_op:
        batch_op.alter_column(
            "role",
            existing_type=sa.Enum(
                "VIEWER", "ANNOTATOR", "EDITOR", "ADMIN", name="collaboratorrole"
            ),
            type_=sa.VARCHAR(length=6),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
