"""empty message

Revision ID: fbcbd179bfba
Revises: 
Create Date: 2025-12-12 11:41:30.859656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types


# revision identifiers, used by Alembic.
revision: str = 'fbcbd179bfba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('project_ids', sa.JSON(), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='projectstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment')),
    sa.UniqueConstraint('id', name=op.f('uq_experiment_id'))
    )
    op.create_table('interviewee',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('interview_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('interview_subject', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interviewee')),
    sa.UniqueConstraint('id', name=op.f('uq_interviewee_id'))
    )
    op.create_table('invitation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitation')),
    sa.UniqueConstraint('email', name=op.f('uq_invitation_email')),
    sa.UniqueConstraint('id', name=op.f('uq_invitation_id'))
    )
    op.create_table('projectfolder',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projectfolder')),
    sa.UniqueConstraint('id', name=op.f('uq_projectfolder_id'))
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_active', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=False),
    sa.Column('scope', sa.Enum('ADMIN', 'USER', 'GUEST', name='scope'), nullable=False),
    sa.Column('invite_token', sa.String(), nullable=True),
    sa.Column('research_consent', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('id', name=op.f('uq_user_id'))
    )
    op.create_table('access_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'FULFILLED', 'DENIED', name='accessrequeststatus'), nullable=False),
    sa.Column('processed_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['processed_by_id'], ['user.id'], name=op.f('fk_access_requests_processed_by_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_requests')),
    sa.UniqueConstraint('email', name=op.f('uq_access_requests_email')),
    sa.UniqueConstraint('id', name=op.f('uq_access_requests_id'))
    )
    op.create_table('collaborator',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('folder_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('added_by_id', sa.Uuid(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('project_role', sa.Enum('ADMIN', 'EDITOR', 'VIEWER', name='projectrole'), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['user.id'], name=op.f('fk_collaborator_added_by_id_user')),
    sa.ForeignKeyConstraint(['folder_id'], ['projectfolder.id'], name=op.f('fk_collaborator_folder_id_projectfolder')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_collaborator_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collaborator')),
    sa.UniqueConstraint('folder_id', 'user_id', name='uq_collaborator'),
    sa.UniqueConstraint('id', name=op.f('uq_collaborator_id'))
    )
    op.create_table('project',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('folder_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='projectstatus'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['projectfolder.id'], name=op.f('fk_project_folder_id_projectfolder')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project')),
    sa.UniqueConstraint('id', name=op.f('uq_project_id')),
    sa.UniqueConstraint('title', 'folder_id', name='title')
    )
    op.create_table('interview',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('interview_guide', sa.JSON(), nullable=False),
    sa.Column('language', app.db.types.LanguageType(length=2), nullable=False),
    sa.Column('interviewer', sa.Enum('HUMAN', 'AI', name='interviewer'), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('total_time_spent', sa.Integer(), nullable=False),
    sa.Column('survey_token', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('referer', sa.String(), nullable=True),
    sa.Column('external_params', sa.String(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('experiment_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], name=op.f('fk_interview_experiment_id_experiment')),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_interview_project_id_project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview')),
    sa.UniqueConstraint('id', 'project_id', name='_unique_interview_ids'),
    sa.UniqueConstraint('id', name=op.f('uq_interview_id'))
    )
    op.create_table('projectlocalization',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('language', app.db.types.LanguageType(length=2), nullable=False),
    sa.Column('consent', sa.JSON(), nullable=True),
    sa.Column('welcome', sa.JSON(), nullable=True),
    sa.Column('interview_guide', sa.JSON(), nullable=False),
    sa.Column('prompts', sa.JSON(), nullable=False),
    sa.Column('agent_configs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_projectlocalization_project_id_project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projectlocalization')),
    sa.UniqueConstraint('id', name=op.f('uq_projectlocalization_id')),
    sa.UniqueConstraint('project_id', 'language', name='unique_project_language')
    )
    with op.batch_alter_table('projectlocalization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projectlocalization_language'), ['language'], unique=False)

    op.create_table('testsetup',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('SHUFFLED_AI', 'FIXED_AI', 'FIXED_ANSWERS', name='testtype'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('language', app.db.types.LanguageType(length=2), nullable=False),
    sa.Column('n_interviews', sa.Integer(), nullable=False),
    sa.Column('answering_model', sa.String(), nullable=True),
    sa.Column('delay_before_answers', sa.JSON(), nullable=True),
    sa.Column('background_info', sa.JSON(), nullable=False),
    sa.Column('fixed_answers', sa.JSON(), nullable=True),
    sa.Column('fixed_personas', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_testsetup_project_id_project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_testsetup')),
    sa.UniqueConstraint('id', name=op.f('uq_testsetup_id'))
    )
    op.create_table('message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('SYSTEM', 'ASSISTANT', 'USER', name='messagerole'), nullable=False),
    sa.Column('interview_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('message_type', sa.Enum('TEXT', 'IMAGE', 'CUSTOM_TOKEN', 'SURVEY_ITEM', name='messagetype'), nullable=False),
    sa.Column('section', sa.Integer(), nullable=True),
    sa.Column('main_question', sa.Integer(), nullable=True),
    sa.Column('sub_question', sa.Integer(), nullable=True),
    sa.Column('is_introduction', sa.Boolean(), nullable=False),
    sa.Column('outro', sa.Boolean(), nullable=False),
    sa.Column('timed', sa.Boolean(), nullable=False),
    sa.Column('can_answer', sa.Boolean(), nullable=False),
    sa.Column('include_in_history', sa.Boolean(), nullable=False),
    sa.Column('attachment', sa.String(), nullable=True),
    sa.Column('feedback', sa.Enum('POSITIVE', 'NEGATIVE', name='feedback'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('image', sa.JSON(), nullable=True),
    sa.Column('survey_item', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interview.id'], name=op.f('fk_message_interview_id_interview')),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_message_project_id_project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message')),
    sa.UniqueConstraint('id', name=op.f('uq_message_id')),
    sa.UniqueConstraint('message_id', 'interview_id', 'project_id', name='_unique_message_ids')
    )
    op.create_table('task',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('time_spend', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interview.id'], name=op.f('fk_task_interview_id_interview')),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_task_project_id_project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task')),
    sa.UniqueConstraint('id', name=op.f('uq_task_id'))
    )
    op.create_table('testrun',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_setup_id', sa.Uuid(), nullable=False),
    sa.Column('language', app.db.types.LanguageType(length=2), nullable=False),
    sa.Column('n_interviews', sa.Integer(), nullable=False),
    sa.Column('answering_model', sa.String(), nullable=True),
    sa.Column('delay_before_answers', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='testrunstatus'), nullable=False),
    sa.ForeignKeyConstraint(['test_setup_id'], ['testsetup.id'], name=op.f('fk_testrun_test_setup_id_testsetup')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_testrun')),
    sa.UniqueConstraint('id', name=op.f('uq_testrun_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testrun')
    op.drop_table('task')
    op.drop_table('message')
    op.drop_table('testsetup')
    with op.batch_alter_table('projectlocalization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projectlocalization_language'))

    op.drop_table('projectlocalization')
    op.drop_table('interview')
    op.drop_table('project')
    op.drop_table('collaborator')
    op.drop_table('access_requests')
    op.drop_table('user')
    op.drop_table('projectfolder')
    op.drop_table('invitation')
    op.drop_table('interviewee')
    op.drop_table('experiment')
    # ### end Alembic commands ###
