"""update participants table

Revision ID: 200b47ae8604
Revises: 8cf6d7def6be
Create Date: 2026-05-05 11:07:10.564647

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "200b47ae8604"
down_revision: Union[str, None] = "8cf6d7def6be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("participant", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "participating",
                sa.Boolean(),
                server_default=sa.text("1"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("participant", schema=None) as batch_op:
        batch_op.drop_column("participating")

    # ### end Alembic commands ###
