"""add ondelete cascade to interview and
  project foreign keys

Revision ID: eb4cc6fea943
Revises: b8c223b73504
Create Date: 2026-02-11 22:15:16.872694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types


# revision identifiers, used by Alembic.
revision: str = 'eb4cc6fea943'
down_revision: Union[str, None] = 'b8c223b73504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_sqliteai_vector')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_message_project_id_project'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_message_interview_id_interview'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_message_project_id_project'), 'project', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_message_interview_id_interview'), 'interview', ['interview_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_task_interview_id_interview'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_task_project_id_project'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_task_interview_id_interview'), 'interview', ['interview_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_task_project_id_project'), 'project', ['project_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_task_project_id_project'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_task_interview_id_interview'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_task_project_id_project'), 'project', ['project_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_task_interview_id_interview'), 'interview', ['interview_id'], ['id'])

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_message_interview_id_interview'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_message_project_id_project'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_message_interview_id_interview'), 'interview', ['interview_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_message_project_id_project'), 'project', ['project_id'], ['id'])

    op.create_table('_sqliteai_vector',
    sa.Column('tblname', sa.TEXT(), nullable=True),
    sa.Column('colname', sa.TEXT(), nullable=True),
    sa.Column('key', sa.TEXT(), nullable=True),
    sa.Column('value', sa.NUMERIC(), nullable=True),
    sa.PrimaryKeyConstraint('tblname', 'colname', 'key')
    )
    # ### end Alembic commands ###
