"""add ondelete cascade to collaborator user FKs

Revision ID: db7e0b1a210b
Revises: 01fdd18d0c82
Create Date: 2026-02-25 14:27:39.346140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types


# revision identifiers, used by Alembic.
revision: str = 'db7e0b1a210b'
down_revision: Union[str, None] = '01fdd18d0c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collaborator', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_collaborator_user_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_collaborator_added_by_id_user'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_collaborator_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_collaborator_added_by_id_user'), 'user', ['added_by_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collaborator', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_collaborator_added_by_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_collaborator_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_collaborator_added_by_id_user'), 'user', ['added_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_collaborator_user_id_user'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
