"""add platform_release table

Revision ID: 477b8b3f841e
Revises: 7a550051f39a
Create Date: 2026-04-10 18:00:11.708600

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "477b8b3f841e"
down_revision: Union[str, None] = "7a550051f39a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "platform_release",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("platform_release_version", sa.String(), nullable=False),
        sa.Column("platform_manifest", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_release")),
        sa.UniqueConstraint("id", name=op.f("uq_platform_release_id")),
        sa.UniqueConstraint(
            "platform_release_version",
            name=op.f("uq_platform_release_platform_release_version"),
        ),
    )
    with op.batch_alter_table("invitation", schema=None) as batch_op:
        batch_op.alter_column(
            "reuseable",
            existing_type=sa.BOOLEAN(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "user_scope",
            existing_type=sa.VARCHAR(length=5),
            server_default=None,
            existing_nullable=False,
        )

    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.alter_column(
            "skipped_by_condition",
            existing_type=sa.BOOLEAN(),
            server_default=None,
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.alter_column(
            "skipped_by_condition",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("0"),
            existing_nullable=False,
        )

    with op.batch_alter_table("invitation", schema=None) as batch_op:
        batch_op.alter_column(
            "user_scope",
            existing_type=sa.VARCHAR(length=5),
            server_default=sa.text("'USER'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "reuseable",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("0"),
            existing_nullable=False,
        )

    op.drop_table("platform_release")
    # ### end Alembic commands ###
