"""add more cascades and relationships to DB

Revision ID: 9874b7e17e42
Revises: eb4cc6fea943
Create Date: 2026-02-12 12:37:38.290701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types


# revision identifiers, used by Alembic.
revision: str = '9874b7e17e42'
down_revision: Union[str, None] = 'eb4cc6fea943'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_sqliteai_vector')
    with op.batch_alter_table('interview', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_interview_test_run_id_testrun'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_interview_experiment_id_experiment'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_interview_experiment_id_experiment'), 'experiment', ['experiment_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_interview_test_run_id_testrun'), 'testrun', ['test_run_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('interviewee', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_interviewee_project_id_project'), 'project', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_interviewee_interview_id_interview'), 'interview', ['interview_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('message_annotation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_message_annotation_message_id_message'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_message_annotation_message_id_message'), 'message', ['message_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_annotation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_message_annotation_message_id_message'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_message_annotation_message_id_message'), 'message', ['message_id'], ['id'])

    with op.batch_alter_table('interviewee', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_interviewee_interview_id_interview'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_interviewee_project_id_project'), type_='foreignkey')

    with op.batch_alter_table('interview', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_interview_test_run_id_testrun'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_interview_experiment_id_experiment'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_interview_experiment_id_experiment'), 'experiment', ['experiment_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_interview_test_run_id_testrun'), 'testrun', ['test_run_id'], ['id'])

    op.create_table('_sqliteai_vector',
    sa.Column('tblname', sa.TEXT(), nullable=True),
    sa.Column('colname', sa.TEXT(), nullable=True),
    sa.Column('key', sa.TEXT(), nullable=True),
    sa.Column('value', sa.NUMERIC(), nullable=True),
    sa.PrimaryKeyConstraint('tblname', 'colname', 'key')
    )
    # ### end Alembic commands ###
