"""update InvitationTable fields

Revision ID: 2d7cafc8b167
Revises: 9736839a677f
Create Date: 2026-02-25 11:21:15.171491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types


# revision identifiers, used by Alembic.
revision: str = '2d7cafc8b167'
down_revision: Union[str, None] = '9736839a677f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_sqliteai_vector')
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reuseable', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('user_scope', sa.Enum('ADMIN', 'USER', 'DEMO', 'GUEST', name='scope'), nullable=False))
        batch_op.add_column(sa.Column('user_expires', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('title')
        batch_op.drop_column('user_expires')
        batch_op.drop_column('user_scope')
        batch_op.drop_column('reuseable')

    op.create_table('_sqliteai_vector',
    sa.Column('tblname', sa.TEXT(), nullable=True),
    sa.Column('colname', sa.TEXT(), nullable=True),
    sa.Column('key', sa.TEXT(), nullable=True),
    sa.Column('value', sa.NUMERIC(), nullable=True),
    sa.PrimaryKeyConstraint('tblname', 'colname', 'key')
    )
    # ### end Alembic commands ###
