"""add assistance session and message chunk tables

Revision ID: 05c658ea7a7a
Revises: f2eb46f01fbf
Create Date: 2026-02-18 10:33:29.786664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types


# revision identifiers, used by Alembic.
revision: str = '05c658ea7a7a'
down_revision: Union[str, None] = 'f2eb46f01fbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistance_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_assistance_session_project_id_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_assistance_session_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assistance_session')),
    sa.UniqueConstraint('id', name=op.f('uq_assistance_session_id'))
    )
    op.create_table('assistance_message_chunk',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('messages_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['assistance_session.id'], name=op.f('fk_assistance_message_chunk_session_id_assistance_session'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assistance_message_chunk')),
    sa.UniqueConstraint('id', name=op.f('uq_assistance_message_chunk_id'))
    )
    op.drop_table('_sqliteai_vector')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('skipped_by_condition',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('skipped_by_condition',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=False)

    op.create_table('_sqliteai_vector',
    sa.Column('tblname', sa.TEXT(), nullable=True),
    sa.Column('colname', sa.TEXT(), nullable=True),
    sa.Column('key', sa.TEXT(), nullable=True),
    sa.Column('value', sa.NUMERIC(), nullable=True),
    sa.PrimaryKeyConstraint('tblname', 'colname', 'key')
    )
    op.drop_table('assistance_message_chunk')
    op.drop_table('assistance_session')
    # ### end Alembic commands ###
