"""scope participants per project and link to interviews

Revision ID: 8cf6d7def6be
Revises: 1da25ee983cf
Create Date: 2026-05-04 18:54:37.404317

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8cf6d7def6be"
down_revision: Union[str, None] = "1da25ee983cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "participant",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("pid", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_participant_project_id_project"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_participant")),
        sa.UniqueConstraint("id", name=op.f("uq_participant_id")),
        sa.UniqueConstraint("project_id", "pid", name="uq_participant_project_pid"),
    )
    with op.batch_alter_table("participant", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_participant_project_id"), ["project_id"], unique=False
        )

    with op.batch_alter_table("interview", schema=None) as batch_op:
        batch_op.add_column(sa.Column("participant_id", sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_interview_participant_id_participant"),
            "participant",
            ["participant_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("interview", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_interview_participant_id_participant"), type_="foreignkey"
        )
        batch_op.drop_column("participant_id")

    with op.batch_alter_table("participant", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_participant_project_id"))

    op.drop_table("participant")
    # ### end Alembic commands ###
