"""add relationship between invitation and AccessRequest

Revision ID: b0d2ed7af240
Revises: 2ef8dd7c8a23
Create Date: 2026-01-06 11:37:37.283071

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types


# revision identifiers, used by Alembic.
revision: str = "b0d2ed7af240"
down_revision: Union[str, None] = "2ef8dd7c8a23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("invitation", schema=None) as batch_op:
        batch_op.add_column(sa.Column("access_request_id", sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_invitation_access_request_id_access_requests"),
            "access_requests",
            ["access_request_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("invitation", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_invitation_access_request_id_access_requests"),
            type_="foreignkey",
        )
        batch_op.drop_column("access_request_id")

    # ### end Alembic commands ###
