"""add lang to participant table

Revision ID: adb83381968c
Revises: f33fb7d53613
Create Date: 2026-05-05 14:37:56.299150

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "adb83381968c"
down_revision: Union[str, None] = "f33fb7d53613"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("participant", schema=None) as batch_op:
        batch_op.add_column(sa.Column("lang", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("participant", schema=None) as batch_op:
        batch_op.drop_column("lang")

    # ### end Alembic commands ###
