"""folder scoped participants with project participant join

Revision ID: 3d64d3a385a1
Revises: 7e9a4a276f53
Create Date: 2026-05-06 13:39:16.100279

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types  # noqa: F401
from app.db.triggers import install_triggers, uninstall_triggers


# revision identifiers, used by Alembic.
revision: str = "3d64d3a385a1"
down_revision: Union[str, None] = "7e9a4a276f53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    # SQLite batch-altering `project` recreates the table, which conflicts
    # with triggers that reference it by name. Drop them upfront and
    # reinstall at the end.
    uninstall_triggers(bind)

    # Wipe existing participant rows and clear stale interview FKs before
    # reshaping the table. Participants are repopulated by the application;
    # historical interview->participant links are intentionally dropped.
    op.execute("UPDATE interview SET participant_id = NULL")
    op.execute("DELETE FROM participant")
    # Folder is now mandatory on projects; drop any project that never got a
    # folder so the NOT NULL constraint can be applied.
    op.execute("DELETE FROM project WHERE folder_id IS NULL")

    op.create_table(
        "project_participant",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("participant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["participant.id"],
            name=op.f("fk_project_participant_participant_id_participant"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_project_participant_project_id_project"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_participant")),
        sa.UniqueConstraint("id", name=op.f("uq_project_participant_id")),
        sa.UniqueConstraint(
            "project_id", "participant_id", name="uq_project_participant"
        ),
    )
    with op.batch_alter_table("project_participant", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_project_participant_participant_id"),
            ["participant_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_project_participant_project_id"),
            ["project_id"],
            unique=False,
        )

    with op.batch_alter_table("interview", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_interview_participant_id_participant"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_interview_participant_id_project_participant"),
            "project_participant",
            ["participant_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("participant", schema=None) as batch_op:
        batch_op.add_column(sa.Column("folder_id", sa.Uuid(), nullable=False))
        batch_op.add_column(sa.Column("opt_out_token", sa.Uuid(), nullable=False))
        batch_op.drop_index(batch_op.f("ix_participant_project_id"))
        batch_op.drop_constraint(
            batch_op.f("uq_participant_project_pid"), type_="unique"
        )
        batch_op.create_index(
            batch_op.f("ix_participant_folder_id"), ["folder_id"], unique=False
        )
        batch_op.create_unique_constraint(
            "uq_participant_folder_pid", ["folder_id", "pid"]
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_participant_opt_out_token"), ["opt_out_token"]
        )
        batch_op.drop_constraint(
            batch_op.f("fk_participant_project_id_project"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_participant_folder_id_projectfolder"),
            "projectfolder",
            ["folder_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("project_id")

    with op.batch_alter_table("project", schema=None) as batch_op:
        batch_op.alter_column(
            "folder_id", existing_type=sa.CHAR(length=32), nullable=False
        )

    install_triggers(bind)
    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    uninstall_triggers(bind)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project", schema=None) as batch_op:
        batch_op.alter_column(
            "folder_id", existing_type=sa.CHAR(length=32), nullable=True
        )

    with op.batch_alter_table("participant", schema=None) as batch_op:
        batch_op.add_column(sa.Column("project_id", sa.CHAR(length=32), nullable=False))
        batch_op.drop_constraint(
            batch_op.f("fk_participant_folder_id_projectfolder"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_participant_project_id_project"),
            "project",
            ["project_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_constraint(
            batch_op.f("uq_participant_opt_out_token"), type_="unique"
        )
        batch_op.drop_constraint("uq_participant_folder_pid", type_="unique")
        batch_op.drop_index(batch_op.f("ix_participant_folder_id"))
        batch_op.create_unique_constraint(
            batch_op.f("uq_participant_project_pid"), ["project_id", "pid"]
        )
        batch_op.create_index(
            batch_op.f("ix_participant_project_id"), ["project_id"], unique=False
        )
        batch_op.drop_column("opt_out_token")
        batch_op.drop_column("folder_id")

    with op.batch_alter_table("interview", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_interview_participant_id_project_participant"),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_interview_participant_id_participant"),
            "participant",
            ["participant_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("project_participant", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_participant_project_id"))
        batch_op.drop_index(batch_op.f("ix_project_participant_participant_id"))

    op.drop_table("project_participant")

    install_triggers(bind)
    # ### end Alembic commands ###
