"""change external_params from str to dict

Revision ID: 1a81ba0cd8c4
Revises: 347e5e37e060
Create Date: 2026-03-12 10:52:46.059264

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1a81ba0cd8c4"
down_revision: Union[str, None] = "347e5e37e060"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("interview", schema=None) as batch_op:
        batch_op.alter_column(
            "external_params",
            existing_type=sa.VARCHAR(),
            type_=sa.JSON(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("interview", schema=None) as batch_op:
        batch_op.alter_column(
            "external_params",
            existing_type=sa.JSON(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
