"""new relationship between interview and testrun

Revision ID: ce37e3db752d
Revises: c0a644746783
Create Date: 2026-01-16 12:34:26.934135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types


# revision identifiers, used by Alembic.
revision: str = 'ce37e3db752d'
down_revision: Union[str, None] = 'c0a644746783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_sqliteai_vector')
    with op.batch_alter_table('interview', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_run_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_interview_test_run_id_testrun'), 'testrun', ['test_run_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_interview_test_run_id_testrun'), type_='foreignkey')
        batch_op.drop_column('test_run_id')

    op.create_table('_sqliteai_vector',
    sa.Column('tblname', sa.TEXT(), nullable=True),
    sa.Column('colname', sa.TEXT(), nullable=True),
    sa.Column('key', sa.TEXT(), nullable=True),
    sa.Column('value', sa.NUMERIC(), nullable=True),
    sa.PrimaryKeyConstraint('tblname', 'colname', 'key')
    )
    # ### end Alembic commands ###
