"""add opt_out_reason to participant table

Revision ID: 0441b03eab18
Revises: 200b47ae8604
Create Date: 2026-05-05 11:33:22.559317

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0441b03eab18"
down_revision: Union[str, None] = "200b47ae8604"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("participant", schema=None) as batch_op:
        batch_op.add_column(sa.Column("opt_out_reason", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("participant", schema=None) as batch_op:
        batch_op.drop_column("opt_out_reason")

    # ### end Alembic commands ###
