"""add newsletter subscription table

Revision ID: 84ab990a0092
Revises: 2f809f10bdb7
Create Date: 2026-05-14 10:07:49.454093

"""

# NOTE: If this migration uses `op.batch_alter_table` against any of `project`,
# `projectlocalization`, `testsetup`, or `testrun` (the tables referenced by
# the touch-last_updated triggers), wrap the upgrade/downgrade bodies with
# `uninstall_triggers(op.get_bind())` before and
# `install_triggers(op.get_bind())` after. SQLite batch-alter renames the
# table, which breaks any trigger that references it by name. See
# `app/db/triggers.py` and revision 3d64d3a385a1 for an example.
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa  # noqa: F401

import app.db.types  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "84ab990a0092"
down_revision: Union[str, None] = "2f809f10bdb7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "newsletter_subscription",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("unsubscribed_at", sa.DateTime(), nullable=True),
        sa.Column("opt_out_token", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_newsletter_subscription")),
        sa.UniqueConstraint("id", name=op.f("uq_newsletter_subscription_id")),
        sa.UniqueConstraint(
            "opt_out_token", name=op.f("uq_newsletter_subscription_opt_out_token")
        ),
    )
    with op.batch_alter_table("newsletter_subscription", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_newsletter_subscription_email"), ["email"], unique=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("newsletter_subscription", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_newsletter_subscription_email"))

    op.drop_table("newsletter_subscription")
    # ### end Alembic commands ###
