"""add participant_email_subject to projectlocalization

Revision ID: 7e9a4a276f53
Revises: adb83381968c
Create Date: 2026-05-05 15:12:44.493747

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "7e9a4a276f53"
down_revision: Union[str, None] = "adb83381968c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projectlocalization", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("participant_email_subject", sa.String(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projectlocalization", schema=None) as batch_op:
        batch_op.drop_column("participant_email_subject")

    # ### end Alembic commands ###
