"""add skipped_by_condition column to MessageTable

Revision ID: f2eb46f01fbf
Revises: 9874b7e17e42
Create Date: 2026-02-16 12:17:11.757070

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types


# revision identifiers, used by Alembic.
revision: str = "f2eb46f01fbf"
down_revision: Union[str, None] = "9874b7e17e42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "skipped_by_condition",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.drop_column("skipped_by_condition")

    op.create_table(
        "_sqliteai_vector",
        sa.Column("tblname", sa.TEXT(), nullable=True),
        sa.Column("colname", sa.TEXT(), nullable=True),
        sa.Column("key", sa.TEXT(), nullable=True),
        sa.Column("value", sa.NUMERIC(), nullable=True),
        sa.PrimaryKeyConstraint("tblname", "colname", "key"),
    )
    # ### end Alembic commands ###
