"""add registration_token to users

Revision ID: 24ce020e2f87
Revises: a9128ba6abfb
Create Date: 2026-06-17 20:18:44.144640

"""

# NOTE: If this migration uses `op.batch_alter_table` against any of `project`,
# `projectlocalization`, `testsetup`, or `testrun` (the tables referenced by
# the touch-last_updated triggers), wrap the upgrade/downgrade bodies with
# `uninstall_triggers(op.get_bind())` before and
# `install_triggers(op.get_bind())` after. SQLite batch-alter renames the
# table, which breaks any trigger that references it by name. See
# `app/db/triggers.py` and revision 3d64d3a385a1 for an example.
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa  # noqa: F401

import app.db.types  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "24ce020e2f87"
down_revision: Union[str, None] = "a9128ba6abfb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("registration_token", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("registration_token")

    # ### end Alembic commands ###
