"""add reminder email templates

Revision ID: 2f809f10bdb7
Revises: 08e271a5c2b5
Create Date: 2026-05-11 15:34:20.637050

"""
# NOTE: If this migration uses `op.batch_alter_table` against any of `project`,
# `projectlocalization`, `testsetup`, or `testrun` (the tables referenced by
# the touch-last_updated triggers), wrap the upgrade/downgrade bodies with
# `uninstall_triggers(op.get_bind())` before and
# `install_triggers(op.get_bind())` after. SQLite batch-alter renames the
# table, which breaks any trigger that references it by name. See
# `app/db/triggers.py` and revision 3d64d3a385a1 for an example.
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa # noqa: F401

import app.db.types # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '2f809f10bdb7'
down_revision: Union[str, None] = '08e271a5c2b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projectlocalization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participant_reminder_email_subject', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('participant_reminder_email_template', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projectlocalization', schema=None) as batch_op:
        batch_op.drop_column('participant_reminder_email_template')
        batch_op.drop_column('participant_reminder_email_subject')

    # ### end Alembic commands ###
