"""add refresh_token table for token rotation

Revision ID: 073a22823ffa
Revises: e5ccbc57a375
Create Date: 2026-03-20 10:52:44.293338

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "073a22823ffa"
down_revision: Union[str, None] = "e5ccbc57a375"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refresh_token",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column("extended", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_refresh_token_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_token")),
        sa.UniqueConstraint("id", name=op.f("uq_refresh_token_id")),
    )
    with op.batch_alter_table("refresh_token", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_refresh_token_family_id"), ["family_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_refresh_token_token_hash"), ["token_hash"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_refresh_token_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("refresh_token", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_refresh_token_user_id"))
        batch_op.drop_index(batch_op.f("ix_refresh_token_token_hash"))
        batch_op.drop_index(batch_op.f("ix_refresh_token_family_id"))

    op.drop_table("refresh_token")
    # ### end Alembic commands ###
