"""get prod up to date

Revision ID: 01fdd18d0c82
Revises: 
Create Date: 2026-02-25 12:40:35.782850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '01fdd18d0c82'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistance_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_assistance_session_project_id_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_assistance_session_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assistance_session')),
    sa.UniqueConstraint('id', name=op.f('uq_assistance_session_id'))
    )
    op.create_table('experiment_project',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], name=op.f('fk_experiment_project_experiment_id_experiment')),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_experiment_project_project_id_project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment_project')),
    sa.UniqueConstraint('experiment_id', 'project_id', name='uq_experiment_project'),
    sa.UniqueConstraint('id', name=op.f('uq_experiment_project_id'))
    )
    op.create_table('assistance_message_chunk',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('messages_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['assistance_session.id'], name=op.f('fk_assistance_message_chunk_session_id_assistance_session'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assistance_message_chunk')),
    sa.UniqueConstraint('id', name=op.f('uq_assistance_message_chunk_id'))
    )
    op.drop_table('_sqliteai_vector')
    with op.batch_alter_table('experiment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Uuid(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_experiment_user_id_user'), 'user', ['user_id'], ['id'])
        batch_op.drop_column('weights')
        batch_op.drop_column('project_ids')

    with op.batch_alter_table('interview', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_interview_experiment_id_experiment'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_interview_test_run_id_testrun'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_interview_experiment_id_experiment'), 'experiment', ['experiment_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_interview_test_run_id_testrun'), 'testrun', ['test_run_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('interviewee', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_interviewee_project_id_project'), 'project', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_interviewee_interview_id_interview'), 'interview', ['interview_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reuseable', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('user_scope', sa.Enum('ADMIN', 'USER', 'DEMO', 'GUEST', name='scope'), nullable=False))
        batch_op.add_column(sa.Column('user_expires', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('expires_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skipped_by_condition', sa.Boolean(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_message_interview_id_interview'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_message_project_id_project'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_message_interview_id_interview'), 'interview', ['interview_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_message_project_id_project'), 'project', ['project_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('message_annotation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_message_annotation_message_id_message'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_message_annotation_message_id_message'), 'message', ['message_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Uuid(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_project_owner_id_user'), 'user', ['owner_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_task_project_id_project'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_task_interview_id_interview'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_task_project_id_project'), 'project', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_task_interview_id_interview'), 'interview', ['interview_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(), nullable=True))
        batch_op.alter_column('invite_token',
               existing_type=sa.VARCHAR(),
               type_=sa.Uuid(),
               existing_nullable=True)
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))
        batch_op.alter_column('invite_token',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_task_interview_id_interview'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_task_project_id_project'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_task_interview_id_interview'), 'interview', ['interview_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_task_project_id_project'), 'project', ['project_id'], ['id'])

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_project_owner_id_user'), type_='foreignkey')
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('message_annotation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_message_annotation_message_id_message'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_message_annotation_message_id_message'), 'message', ['message_id'], ['id'])

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_message_project_id_project'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_message_interview_id_interview'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_message_project_id_project'), 'project', ['project_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_message_interview_id_interview'), 'interview', ['interview_id'], ['id'])
        batch_op.drop_column('skipped_by_condition')

    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('title')
        batch_op.drop_column('user_expires')
        batch_op.drop_column('user_scope')
        batch_op.drop_column('reuseable')

    with op.batch_alter_table('interviewee', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_interviewee_interview_id_interview'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_interviewee_project_id_project'), type_='foreignkey')

    with op.batch_alter_table('interview', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_interview_test_run_id_testrun'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_interview_experiment_id_experiment'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_interview_test_run_id_testrun'), 'testrun', ['test_run_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_interview_experiment_id_experiment'), 'experiment', ['experiment_id'], ['id'])

    with op.batch_alter_table('experiment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_ids', sqlite.JSON(), nullable=False))
        batch_op.add_column(sa.Column('weights', sqlite.JSON(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_experiment_user_id_user'), type_='foreignkey')
        batch_op.drop_column('user_id')

    op.create_table('_sqliteai_vector',
    sa.Column('tblname', sa.TEXT(), nullable=True),
    sa.Column('colname', sa.TEXT(), nullable=True),
    sa.Column('key', sa.TEXT(), nullable=True),
    sa.Column('value', sa.NUMERIC(), nullable=True),
    sa.PrimaryKeyConstraint('tblname', 'colname', 'key')
    )
    op.drop_table('assistance_message_chunk')
    op.drop_table('experiment_project')
    op.drop_table('assistance_session')
    # ### end Alembic commands ###
