"""add pareticipant_email_template to projectlocalization table

Revision ID: f33fb7d53613
Revises: 0441b03eab18
Create Date: 2026-05-05 12:14:41.626070

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db.types  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = "f33fb7d53613"
down_revision: str | None = "0441b03eab18"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projectlocalization", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("participant_email_template", sa.String(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projectlocalization", schema=None) as batch_op:
        batch_op.drop_column("participant_email_template")

    # ### end Alembic commands ###
