"""add embedding table

Revision ID: 8433cc9ebf8e
Revises: 3c9a1e77b204
Create Date: 2026-09-01 14:50:28.075918

"""

# NOTE: If this migration uses `op.batch_alter_table` against any of `project`,
# `projectlocalization`, `testsetup`, or `testrun` (the tables referenced by
# the touch-last_updated triggers), wrap the upgrade/downgrade bodies with
# `uninstall_triggers(op.get_bind())` before and
# `install_triggers(op.get_bind())` after. SQLite batch-alter renames the
# table, which breaks any trigger that references it by name. See
# `app/db/triggers.py` and revision 3d64d3a385a1 for an example.
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db.types

# revision identifiers, used by Alembic.
revision: str = "8433cc9ebf8e"
down_revision: str | None = "3c9a1e77b204"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "embedding",
        sa.Column(
            "kind",
            sa.Enum("MESSAGE", "QA_PAIR", "SECTION", "INTERVIEW", name="embeddingkind"),
            nullable=False,
        ),
        sa.Column(
            "task",
            sa.Enum("DOCUMENT", "CLUSTERING", name="embeddingtask"),
            nullable=False,
        ),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("interview_id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=True),
        sa.Column("section", sa.Integer(), nullable=True),
        sa.Column("main_question", sa.Integer(), nullable=True),
        sa.Column("sub_question", sa.Integer(), nullable=True),
        sa.Column("language", app.db.types.LanguageType(length=2), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("format_version", sa.String(), server_default="1", nullable=False),
        sa.Column("dim", sa.Integer(), nullable=False),
        sa.Column("chunk_key", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("vector", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["interview_id"],
            ["interview.id"],
            name=op.f("fk_embedding_interview_id_interview"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["message.id"],
            name=op.f("fk_embedding_message_id_message"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_embedding_project_id_project"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_embedding")),
        sa.UniqueConstraint("chunk_key", name="uq_embedding_chunk_key"),
        sa.UniqueConstraint("id", name=op.f("uq_embedding_id")),
    )
    with op.batch_alter_table("embedding", schema=None) as batch_op:
        batch_op.create_index(
            "ix_embedding_content_hash", ["content_hash"], unique=False
        )
        batch_op.create_index(
            "ix_embedding_interview_id", ["interview_id"], unique=False
        )
        batch_op.create_index(
            "ix_embedding_project_id_kind_task",
            ["project_id", "kind", "task"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("embedding", schema=None) as batch_op:
        batch_op.drop_index("ix_embedding_project_id_kind_task")
        batch_op.drop_index("ix_embedding_interview_id")
        batch_op.drop_index("ix_embedding_content_hash")

    op.drop_table("embedding")
    # ### end Alembic commands ###
