"""fix interview type

Revision ID: c0a644746783
Revises: b0d2ed7af240
Create Date: 2026-01-08 21:03:01.593563

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types


# revision identifiers, used by Alembic.
revision: str = "c0a644746783"
down_revision: Union[str, None] = "b0d2ed7af240"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("interview", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "type",
                sa.Enum("TEST", "SYNTHETIC", "DISTRIBUTED", name="interviewtype"),
                nullable=True,
            )
        )

    op.execute(sa.text("UPDATE interview SET type = 'DISTRIBUTED'"))
    op.execute(
        sa.text("UPDATE interview SET type = 'SYNTHETIC' WHERE is_synthetic = true")
    )
    op.execute(sa.text("UPDATE interview SET type = 'TEST' WHERE is_test = true"))

    with op.batch_alter_table("interview", schema=None) as batch_op:
        batch_op.alter_column("type", nullable=False)
        batch_op.drop_column("is_test")
        batch_op.drop_column("is_synthetic")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("interview", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_synthetic",
                sa.BOOLEAN(),
                server_default=sa.text("false"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "is_test", sa.BOOLEAN(), server_default=sa.text("false"), nullable=False
            )
        )

    op.execute(
        sa.text("UPDATE interview SET is_synthetic = true WHERE type = 'SYNTHETIC'")
    )
    op.execute(sa.text("UPDATE interview SET is_test = true WHERE type = 'TEST'"))

    with op.batch_alter_table("interview", schema=None) as batch_op:
        batch_op.drop_column("type")
    # ### end Alembic commands ###
