"""add platform_version to interview

Revision ID: 0aeedbbaa569
Revises: 477b8b3f841e
Create Date: 2026-04-13 14:09:01.500454

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0aeedbbaa569"
down_revision: Union[str, None] = "477b8b3f841e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("interview", schema=None) as batch_op:
        batch_op.add_column(sa.Column("platform_version", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("interview", schema=None) as batch_op:
        batch_op.drop_column("platform_version")

    # ### end Alembic commands ###
