"""cascade delete projects when folder is deleted

Revision ID: 08e271a5c2b5
Revises: 3d64d3a385a1
Create Date: 2026-05-06 14:00:04.635502

"""

from typing import Sequence, Union

from alembic import op

import app.db.types  # noqa: F401
from app.db.triggers import install_triggers, uninstall_triggers


# revision identifiers, used by Alembic.
revision: str = "08e271a5c2b5"
down_revision: Union[str, None] = "3d64d3a385a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    # SQLite batch-altering `project` recreates the table; triggers that
    # reference it by name break during the rename. Drop and reinstall.
    uninstall_triggers(bind)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_project_folder_id_projectfolder"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_project_folder_id_projectfolder"),
            "projectfolder",
            ["folder_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###
    install_triggers(bind)


def downgrade() -> None:
    bind = op.get_bind()
    uninstall_triggers(bind)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_project_folder_id_projectfolder"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_project_folder_id_projectfolder"),
            "projectfolder",
            ["folder_id"],
            ["id"],
        )

    # ### end Alembic commands ###
    install_triggers(bind)
