"""add extra user columns

Revision ID: 790569df2e3e
Revises: db7e0b1a210b
Create Date: 2026-02-26 10:39:47.447873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types


# revision identifiers, used by Alembic.
revision: str = '790569df2e3e'
down_revision: Union[str, None] = 'db7e0b1a210b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invitation_title', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('access_request_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('admin_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('admin_note_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('admin_note_updated_at')
        batch_op.drop_column('admin_note')
        batch_op.drop_column('access_request_message')
        batch_op.drop_column('expires_at')
        batch_op.drop_column('invitation_title')

    # ### end Alembic commands ###
