"""force answering_model for TestSetupTable

Revision ID: 2ef8dd7c8a23
Revises: 64a392d65079
Create Date: 2026-01-05 14:51:12.624649

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types
from ainterviewer.settings import settings as lib_settings


# revision identifiers, used by Alembic.
revision: str = "2ef8dd7c8a23"
down_revision: Union[str, None] = "64a392d65079"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Backfill existing NULLs
    op.execute(
        f"""
        UPDATE testsetup
        SET answering_model = '{lib_settings.llm.default_model}'
        WHERE answering_model IS NULL
        """
    )

    # 2. Enforce NOT NULL
    with op.batch_alter_table("testsetup") as batch_op:
        batch_op.alter_column(
            "answering_model",
            existing_type=sa.VARCHAR(),
            nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("testsetup", schema=None) as batch_op:
        batch_op.alter_column(
            "answering_model", existing_type=sa.VARCHAR(), nullable=True
        )

    # ### end Alembic commands ###
