"""change invite_token type to UUID in UserTable

Revision ID: 66c0a69c8c4c
Revises: 8ddc73cff870
Create Date: 2026-02-25 11:34:22.832690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types


# revision identifiers, used by Alembic.
revision: str = '66c0a69c8c4c'
down_revision: Union[str, None] = '8ddc73cff870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_sqliteai_vector')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('invite_token',
               existing_type=sa.VARCHAR(),
               type_=sa.Uuid(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('invite_token',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    op.create_table('_sqliteai_vector',
    sa.Column('tblname', sa.TEXT(), nullable=True),
    sa.Column('colname', sa.TEXT(), nullable=True),
    sa.Column('key', sa.TEXT(), nullable=True),
    sa.Column('value', sa.NUMERIC(), nullable=True),
    sa.PrimaryKeyConstraint('tblname', 'colname', 'key')
    )
    # ### end Alembic commands ###
