"""add pareticipant_email_template to projectlocalization table

Revision ID: f33fb7d53613
Revises: 0441b03eab18
Create Date: 2026-05-05 12:14:41.626070

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "f33fb7d53613"
down_revision: Union[str, None] = "0441b03eab18"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projectlocalization", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("participant_email_template", sa.String(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projectlocalization", schema=None) as batch_op:
        batch_op.drop_column("participant_email_template")

    # ### end Alembic commands ###
