"""add email verification and login 2fa

Revision ID: d59584c07ecb
Revises: 24ce020e2f87
Create Date: 2026-06-23 10:23:22.257512

"""

# NOTE: If this migration uses `op.batch_alter_table` against any of `project`,
# `projectlocalization`, `testsetup`, or `testrun` (the tables referenced by
# the touch-last_updated triggers), wrap the upgrade/downgrade bodies with
# `uninstall_triggers(op.get_bind())` before and
# `install_triggers(op.get_bind())` after. SQLite batch-alter renames the
# table, which breaks any trigger that references it by name. See
# `app/db/triggers.py` and revision 3d64d3a385a1 for an example.
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa  # noqa: F401

import app.db.types  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "d59584c07ecb"
down_revision: Union[str, None] = "24ce020e2f87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verification_code",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("code_hash", sa.String(), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum("EMAIL_VERIFICATION", "LOGIN", name="verificationpurpose"),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("consumed_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_verification_code_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_code")),
        sa.UniqueConstraint("id", name=op.f("uq_verification_code_id")),
    )
    with op.batch_alter_table("verification_code", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_verification_code_code_hash"), ["code_hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_verification_code_user_id"), ["user_id"], unique=False
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "email_verified",
                sa.Boolean(),
                server_default=sa.text("0"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "two_factor_enabled",
                sa.Boolean(),
                server_default=sa.text("1"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###

    # Grandfather existing accounts: they registered before email verification
    # existed, so mark them verified to avoid locking them out of login.
    op.execute('UPDATE "user" SET email_verified = 1')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("two_factor_enabled")
        batch_op.drop_column("email_verified")

    with op.batch_alter_table("verification_code", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_verification_code_user_id"))
        batch_op.drop_index(batch_op.f("ix_verification_code_code_hash"))

    op.drop_table("verification_code")
    # ### end Alembic commands ###
