"""new interview_status column

Revision ID: 268a6e6492c3
Revises: ce37e3db752d
Create Date: 2026-01-16 16:26:15.468079

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types
from ainterviewer.types import InterviewStatus


# revision identifiers, used by Alembic.
revision: str = "268a6e6492c3"
down_revision: Union[str, None] = "ce37e3db752d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("_sqliteai_vector")
    with op.batch_alter_table("interview", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "status",
                sa.Enum("ACTIVE", "INACTIVE", "COMPLETED", name="interviewstatus"),
                nullable=True,
            )
        )

    # Data migration
    interview = sa.Table(
        "interview",
        sa.MetaData(),
        sa.Column("id", sa.Uuid),
        sa.Column("is_active", sa.Boolean),
        sa.Column("is_complete", sa.Boolean),
        sa.Column(
            "status", sa.Enum("ACTIVE", "INACTIVE", "COMPLETED", name="interviewstatus")
        ),
    )

    connection = op.get_bind()
    connection.execute(
        interview.update().values(
            status=sa.case(
                (interview.c.is_complete == True, "COMPLETED"),
                (interview.c.is_active == True, "ACTIVE"),
                else_="INACTIVE",
            )
        )
    )

    with op.batch_alter_table("interview", schema=None) as batch_op:
        batch_op.alter_column("status", nullable=False)
        batch_op.alter_column(
            "type",
            existing_type=sa.VARCHAR(length=11),
            type_=sa.Enum(
                "MANUAL_TEST", "SYNTHETIC_TEST", "DISTRIBUTED", name="interviewtype"
            ),
            existing_nullable=False,
        )
        batch_op.drop_column("is_complete")
        batch_op.drop_column("is_active")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("interview", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_active", sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column("is_complete", sa.BOOLEAN(), nullable=True))

    # Data migration
    interview = sa.Table(
        "interview",
        sa.MetaData(),
        sa.Column("id", sa.Uuid),
        sa.Column("is_active", sa.Boolean),
        sa.Column("is_complete", sa.Boolean),
        sa.Column(
            "status", sa.Enum("ACTIVE", "INACTIVE", "COMPLETED", name="interviewstatus")
        ),
    )

    connection = op.get_bind()
    connection.execute(
        interview.update().values(
            is_complete=sa.case((interview.c.status == "COMPLETED", True), else_=False),
            is_active=sa.case((interview.c.status == "ACTIVE", True), else_=False),
        )
    )

    with op.batch_alter_table("interview", schema=None) as batch_op:
        batch_op.alter_column("is_active", nullable=False)
        batch_op.alter_column("is_complete", nullable=False)
        batch_op.alter_column(
            "type",
            existing_type=sa.Enum(
                "MANUAL_TEST", "SYNTHETIC_TEST", "DISTRIBUTED", name="interviewtype"
            ),
            type_=sa.VARCHAR(length=11),
            existing_nullable=False,
        )
        batch_op.drop_column("status")

    op.create_table(
        "_sqliteai_vector",
        sa.Column("tblname", sa.TEXT(), nullable=True),
        sa.Column("colname", sa.TEXT(), nullable=True),
        sa.Column("key", sa.TEXT(), nullable=True),
        sa.Column("value", sa.NUMERIC(), nullable=True),
        sa.PrimaryKeyConstraint("tblname", "colname", "key"),
    )
    # ### end Alembic commands ###
