"""update user_expires column type

Revision ID: 8ddc73cff870
Revises: 2d7cafc8b167
Create Date: 2026-02-25 11:26:44.401265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types


# revision identifiers, used by Alembic.
revision: str = '8ddc73cff870'
down_revision: Union[str, None] = '2d7cafc8b167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_sqliteai_vector')
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('user_expires',
               existing_type=sa.DATETIME(),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.alter_column('user_expires',
               existing_type=sa.JSON(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('expires_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    op.create_table('_sqliteai_vector',
    sa.Column('tblname', sa.TEXT(), nullable=True),
    sa.Column('colname', sa.TEXT(), nullable=True),
    sa.Column('key', sa.TEXT(), nullable=True),
    sa.Column('value', sa.NUMERIC(), nullable=True),
    sa.PrimaryKeyConstraint('tblname', 'colname', 'key')
    )
    # ### end Alembic commands ###
