"""change name to first_name last_name instead

Revision ID: 77c4a96153cb
Revises: 05c658ea7a7a
Create Date: 2026-02-18 15:34:15.181968

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types


# revision identifiers, used by Alembic.
revision: str = "77c4a96153cb"
down_revision: Union[str, None] = "05c658ea7a7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("_sqliteai_vector")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("first_name", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("last_name", sa.String(), nullable=True))

    op.execute(
        """
        UPDATE user
        SET first_name = CASE
            WHEN instr(name, ' ') > 0 THEN trim(substr(name, 1, instr(name, ' ') - 1))
            ELSE name
        END,
        last_name = CASE
            WHEN instr(name, ' ') > 0 THEN trim(substr(name, instr(name, ' ') + 1))
            ELSE NULL
        END
        """
    )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column("first_name", nullable=False)
        batch_op.drop_column("name")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.VARCHAR(), nullable=True))

    op.execute(
        """
        UPDATE user
        SET name = CASE
            WHEN last_name IS NULL OR trim(last_name) = '' THEN trim(coalesce(first_name, ''))
            ELSE trim(coalesce(first_name, '') || ' ' || coalesce(last_name, ''))
        END
        """
    )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column("name", nullable=False)
        batch_op.drop_column("last_name")
        batch_op.drop_column("first_name")

    op.create_table(
        "_sqliteai_vector",
        sa.Column("tblname", sa.TEXT(), nullable=True),
        sa.Column("colname", sa.TEXT(), nullable=True),
        sa.Column("key", sa.TEXT(), nullable=True),
        sa.Column("value", sa.NUMERIC(), nullable=True),
        sa.PrimaryKeyConstraint("tblname", "colname", "key"),
    )
    # ### end Alembic commands ###
