from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field


class GitHashes(BaseModel):
    core_lib: str
    backend: str
    frontend: str


class ComponentChange(BaseModel):
    """One component release that landed in a platform release.

    `groups` maps a changelog section ("Features", "Bug Fixes", ...) to its
    entries, as generated by git-cliff and published in the component's GitHub
    Release. Only user-visible sections are carried here, and a release with
    nothing user-visible is omitted entirely — the version it shipped is already
    recorded in the manifest's component fields.
    """

    version: str
    date: datetime | None = None
    groups: dict[str, list[str]] = Field(default_factory=dict)


class ReleaseNotes(BaseModel):
    """Component changes between the previously deployed platform release and this one.

    A component that did not move between deploys has an empty list. Note that
    `core_lib` tracks the version the backend actually depends on (read from its
    uv.lock), which lags the lib repo's own latest tag whenever the backend has
    not yet bumped its pin.
    """

    core_lib: list[ComponentChange] = Field(default_factory=list)
    backend: list[ComponentChange] = Field(default_factory=list)
    frontend: list[ComponentChange] = Field(default_factory=list)


class Highlight(BaseModel):
    """One user-facing change in a platform release.

    Deliberately carries no component or version: a single change often spans
    backend and frontend, and a user has no use for either fact. `notes` keeps
    the per-component provenance for support and debugging.
    """

    kind: Literal["new", "improved", "fixed"]
    title: str
    body: str | None = None


class PlatformManifest(BaseModel):
    platform_version: str
    core_lib: str
    backend: str
    frontend: str
    build_time: datetime
    git: GitHashes
    # Optional so manifests stored before release notes existed still validate,
    # and so a deploy whose notes could not be fetched is still insertable.
    notes: ReleaseNotes | None = None
    # Curated, user-facing rewrite of `notes`. None means "not curated yet";
    # an empty list means "curated, and nothing here concerns users".
    highlights: list[Highlight] | None = None


class PlatformRelease(BaseModel):
    """What the app shows a user: no components, no versions, no hashes."""

    platform_version: str
    released_at: datetime
    highlights: list[Highlight]
